#!/usr/bin/env node
// Copies packages/core/src into supabase/functions/_shared/core so Edge Functions
// (Deno) run exactly the same domain code as the app. The Supabase CLI only
// bundles files inside supabase/functions, so a copy is required.
//
//   node scripts/sync-core.mjs          write the copy
//   node scripts/sync-core.mjs --check  fail if the copy is stale (CI)
import { mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(root, 'packages/core/src');
const target = join(root, 'supabase/functions/_shared/core');
const check = process.argv.includes('--check');
const HEADER = '// GENERATED by scripts/sync-core.mjs from packages/core/src — do not edit.\n';

function collect(dir) {
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) return collect(path);
    return name.endsWith('.ts') && !name.endsWith('.test.ts') ? [path] : [];
  });
}

const expected = new Map(
  collect(source).map((file) => [relative(source, file).replaceAll('\\', '/'), HEADER + readFileSync(file, 'utf8')]),
);

if (check) {
  const actual = existsSync(target)
    ? new Map(collect(target).map((file) => [relative(target, file).replaceAll('\\', '/'), readFileSync(file, 'utf8')]))
    : new Map();
  const stale = [...expected].filter(([path, content]) => actual.get(path) !== content).map(([path]) => path);
  const extra = [...actual.keys()].filter((path) => !expected.has(path));
  if (stale.length || extra.length) {
    console.error('supabase/functions/_shared/core is out of date. Run `pnpm sync:core`.', { stale, extra });
    process.exit(1);
  }
  console.log('core copy is up to date');
} else {
  rmSync(target, { recursive: true, force: true });
  for (const [path, content] of expected) {
    const file = join(target, path);
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
  console.log(`synced ${expected.size} files → supabase/functions/_shared/core`);
}
